"""EXACT: a finite "planted allotrope" for the model's author's dark-matter picture, and the cheapest switches out of it.
Usage:

    python scripts/build_planted_allotrope.py                 # the report (about a minute)
    python scripts/build_planted_allotrope.py --neutral       # also: does one zero-cost switch open a downhill one?
    python scripts/build_planted_allotrope.py --descend 12    # also a zero-temperature path out of each planted state
    python scripts/build_planted_allotrope.py --size 720      # the same objects on a larger background
    python scripts/build_planted_allotrope.py --save DIR      # write each graph as DIR/<name>.npz (adj, part)

Written 2026-09-25 for the design note docs/design/planted_allotrope.md (piece 12, after T36 / O59). Nothing here is
a simulation: every number is counted on a fixed graph.

WHAT THE ALLOTROPE IS ([T25] Sec. VI.3 and Fig. 9; [T24] Sec. V and Fig. 1; read from the arXiv HTML on
2026-09-25). The background is a tiling in which every point is the corner of three squares and one hexagon ([T25]
Sec. IV.2 and Fig. 7). The allotrope in Fig. 9 is one hexagon whose six corners each touch two squares and two
hexagons, the squares on opposite sides; every other point keeps three squares. The figure lives on the infinite
hyperbolic plane. This script builds finite, closed versions.

THE BACKGROUND, FINITE (ours). The Fig. 7 tiling is the Cayley graph of the group <a, b | a^6 = b^4 = (b^-1 a)^2 = 1>
with generators a, b: the a-cycles are the hexagons, the b-cycles are the squares that touch hexagons only at corners,
and the relation (b^-1 a)^2 = 1 gives the squares along hexagon edges. Any finite group generated by two permutations
with those orders and that relation gives a finite graph in which every point has exactly this neighbourhood, provided
no extra short cycles appear; that is checked, not assumed. Both generators are odd permutations, so the sign of a
permutation 2-colours the graph (bipartite). The generators below were found by a random search among permutations of
10 or 11 points (seed 1, in a scratch script; not needed to rebuild anything) and are fixed here. N = 240 matches the
infinite tiling out to graph distance 5 from every point (ball sizes 1, 5, 14, 31, 61, 113).

THE ALLOTROPE, PLANTED (ours). Read as a map, the background has hexagonal faces (the a-cycles) and vertices of degree 4
(the b-squares are those vertices, cut off). A Fig. 9 allotrope is a vertex of degree 6: its cut-off corner is a
hexagon instead of a square. Two surgeries make such vertices without touching anything else:
  * handle: delete two far-apart hexagons (12 points) and join the 24 freed links across. Six vertices become degree 6,
    so 36 points touch two squares: six Fig. 9 allotropes fused in a ring around a new handle.
  * fold (cross-cap): delete one hexagon (6 points) and join the freed links of opposite corners. Three vertices become
    degree 6: 18 points, three Fig. 9 allotropes fused in a triangle. The smallest this script makes.
A single Fig. 9 allotrope alone needs N = 18 mod 24 on an orientable map (ours: the sign of a permutation; see the
note); it is not built here.
The same handle surgery on the flat lattice torus (T36's 14 x 14) makes points touching three squares, of exactly the
background's kind, in points touching four: the same allotrope one rung up.

THE WALLS. Every switch (u1, v1), (u2, v2) -> (u1, v2), (u2, v1) with u1 on side 0 near the planted region and u2
within graph distance 4 of u1 is tried and priced at dH = -16 dS + 4 lam dX (ASSUMPTIONS Q1; lam = 1, the published
model). Distance 4 catches every switch that gains a square or costs less than 32 (a switch gains a square only if
the new link closes one, which needs u1 within 3 of v2); cheaper-than-32 switches are all that is reported.
"""
import argparse
import itertools
import sys
from collections import Counter
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from graphity.cqg import NO_CAP, torus                                          # noqa: E402
from graphity.cqg_d import _switch, hamiltonian, is_valid, surplus, total_squares   # noqa: E402
from graphity.squares import squares_on_edge                                    # noqa: E402

LAM = 1.0            # the published model (VISION Update 22's naming condition: this is CQG)

# Generators (a, b) as images of 0..n-1: a has order 6, b order 4, (b^-1 a)^2 = 1, both odd. Found 2026-09-25.
GROUPS = {
    240: ([6, 2, 0, 3, 5, 1, 4, 7, 8, 9], [4, 0, 2, 7, 5, 1, 6, 3, 9, 8]),
    720: ([7, 3, 2, 1, 8, 0, 6, 5, 9, 4], [0, 5, 6, 1, 4, 7, 2, 3, 9, 8]),
    1152: ([3, 7, 6, 9, 5, 0, 2, 1, 4, 8], [3, 1, 8, 0, 5, 9, 4, 7, 2, 6]),
}


# ---------------------------------------------------------------------------------------------- building graphs
def _mul(g, h):
    """g then h."""
    return tuple(h[i] for i in g)


def _inv(g):
    r = [0] * len(g)
    for i, x in enumerate(g):
        r[x] = i
    return tuple(r)


def _two_colour(adj):
    n = adj.shape[0]
    col = -np.ones(n, dtype=np.int64)
    for s in range(n):
        if col[s] >= 0:
            continue
        col[s] = 0
        stack = [s]
        while stack:
            v = stack.pop()
            for w in adj[v]:
                w = int(w)
                if col[w] < 0:
                    col[w] = 1 - col[v]
                    stack.append(w)
                elif col[w] == col[v]:
                    return None
    return col


def background(size=240):
    """The finite Fig. 7 tiling: adjacency (N, 4) and sides. Slots: g*a, g*a^-1, g*b, g*b^-1 (slot 0 walks a hexagon)."""
    a, b = (tuple(x) for x in GROUPS[size])
    ai, bi = _inv(a), _inv(b)
    e = tuple(range(len(a)))
    index, elems, queue = {e: 0}, [e], [e]
    while queue:                                     # breadth-first closure: a fixed numbering
        g = queue.pop(0)
        for s in (a, ai, b, bi):
            h = _mul(g, s)
            if h not in index:
                index[h] = len(elems)
                elems.append(h)
                queue.append(h)
    adj = np.array([[index[_mul(g, s)] for s in (a, ai, b, bi)] for g in elems], dtype=np.int64)
    part = _two_colour(adj)
    if part is None or len(elems) != size:
        raise RuntimeError("background group does not give the expected bipartite graph")
    return adj, part


def hexagon(adj, g):
    """The a-cycle (map face) through point g, in cyclic order."""
    out = [int(g)]
    for _ in range(5):
        out.append(int(adj[out[-1], 0]))
    if int(adj[out[-1], 0]) != out[0]:
        raise RuntimeError("slot 0 does not close a hexagon")
    return out


def distances(adj, sources):
    d = -np.ones(adj.shape[0], dtype=np.int64)
    frontier = [int(s) for s in sources]
    d[frontier] = 0
    while frontier:
        nxt = []
        for x in frontier:
            for w in adj[x]:
                if d[w] < 0:
                    d[w] = d[x] + 1
                    nxt.append(int(w))
        frontier = nxt
    return d


def square_counts(adj):
    """c(v): the squares containing v, = (sum of squares on v's links) / 2."""
    return np.array([sum(int(squares_on_edge(adj, v, int(w))) for w in adj[v]) // 2 for v in range(adj.shape[0])])


def link_pattern(adj, v):
    """Squares on each of v's four links, sorted: (1, 1, 2, 2) for a background point, (1, 1, 1, 1) for Fig. 9's."""
    return tuple(sorted(int(squares_on_edge(adj, v, int(w))) for w in adj[v]))


def _rewire(adj, removed, joins):
    """Delete the points `removed`; `joins` lists (x, y, fx, fy): x's link to the removed fx becomes a link to y, and
    y's link to the removed fy a link to x. Returns the renumbered graph, or None if it is not 4-regular and simple."""
    new = adj.copy()
    for x, y, fx, fy in joins:
        new[x][list(new[x]).index(fx)] = y
        new[y][list(new[y]).index(fy)] = x
    gone = set(removed)
    keep = np.array([v for v in range(adj.shape[0]) if v not in gone])
    renum = -np.ones(adj.shape[0], dtype=np.int64)
    renum[keep] = np.arange(len(keep))
    sub = renum[new[keep]]
    if (sub < 0).any() or any(len(set(r.tolist())) != 4 for r in sub):
        return None
    return sub.astype(np.int64)


def _outer(adj, face):
    fs = set(face)
    return [[int(w) for w in adj[p] if int(w) not in fs] for p in face]


def _accept(new, bg_c, expected):
    """Keep a candidate only if it is bipartite and valid, and exactly `expected` points sit one square below bg_c."""
    if new is None or _two_colour(new) is None or not is_valid(new):
        return False
    c = square_counts(new)
    return int((c == bg_c - 1).sum()) == expected and int((c < bg_c - 1).sum()) == 0 and int((c > bg_c).sum()) == 0


def glue(adj, f, g, bg_c, expected):
    """Handle: delete faces f and g, join the freed links across. First candidate (fixed order) that meets the profile."""
    n_f = len(f)
    of, og = _outer(adj, f), _outer(adj, g)
    for sgn in (1, -1):
        for off in range(n_f):
            for cross in itertools.product((0, 1), repeat=n_f):
                joins = []
                for i in range(n_f):
                    j = (off + sgn * i) % n_f
                    y0, y1 = og[j] if cross[i] == 0 else og[j][::-1]
                    joins += [(of[i][0], y0, f[i], g[j]), (of[i][1], y1, f[i], g[j])]
                new = _rewire(adj, f + g, joins)
                if _accept(new, bg_c, expected):
                    return new, (sgn, off, cross)
    raise RuntimeError("no gluing meets the profile")


def fold(adj, f, bg_c, expected):
    """Cross-cap: delete face f, join the freed links of opposite corners. First candidate that meets the profile."""
    h = len(f) // 2
    of = _outer(adj, f)
    for cross in itertools.product((0, 1), repeat=h):
        joins = []
        for i in range(h):
            y0, y1 = of[i + h] if cross[i] == 0 else of[i + h][::-1]
            joins += [(of[i][0], y0, f[i], f[i + h]), (of[i][1], y1, f[i], f[i + h])]
        new = _rewire(adj, f, joins)
        if _accept(new, bg_c, expected):
            return new, cross
    raise RuntimeError("no fold meets the profile")


def far_face(adj, f, faces):
    d = distances(adj, f)
    return max(faces, key=lambda h: (min(d[h]), -min(h)))


def build_all(size=240, flat_side=14):
    """{name: (adj, part, background square count)} for the five objects of the note."""
    out = {}
    bg, bpart = background(size)
    out["hyperbolic_background"] = (bg, bpart, 3)
    faces = {}
    for g in range(bg.shape[0]):
        h = hexagon(bg, g)
        faces.setdefault(min(h), h)
    f0 = hexagon(bg, 0)
    f1 = far_face(bg, f0, [h for k, h in faces.items() if k != min(f0)])
    new, _ = fold(bg, f0, 3, 18)
    out["hyperbolic_fold"] = (new, _two_colour(new), 3)
    new, _ = glue(bg, f0, f1, 3, 36)
    out["hyperbolic_handle"] = (new, _two_colour(new), 3)
    L = flat_side
    flat, fpart = torus(L, L, NO_CAP)
    out["flat_torus"] = (flat, fpart, 4)

    def sq(x, y):                                 # a lattice square with an (even, even) corner: a map face
        return [(x % L) * L + y % L, ((x + 1) % L) * L + y % L, ((x + 1) % L) * L + (y + 1) % L, (x % L) * L + (y + 1) % L]
    h = (L // 2) - ((L // 2) % 2)
    new, _ = glue(flat, sq(0, 0), sq(h, h), 4, 24)
    out["flat_handle"] = (new, _two_colour(new), 4)
    return out


# ---------------------------------------------------------------------------------------------- the walls
def switches(adj, part, u1s, near=4, lam=LAM):
    """Every valid switch with u1 in u1s (side 0) and u2 within `near` of u1, each counted once.
    Returns [(dH, dS, dX, u1, v1, u2, v2)]."""
    s0, x0 = int(total_squares(adj)), int(surplus(adj))
    seen, out = set(), []
    for u1 in u1s:
        u1 = int(u1)
        d = distances(adj, [u1])
        nb1 = set(int(v) for v in adj[u1])
        for u2 in np.flatnonzero((part == 0) & (d > 0) & (d <= near)):
            u2 = int(u2)
            nb2 = set(int(v) for v in adj[u2])
            for v1 in adj[u1]:
                v1 = int(v1)
                if v1 in nb2:
                    continue
                for v2 in adj[u2]:
                    v2 = int(v2)
                    if v2 == v1 or v2 in nb1:
                        continue
                    key = tuple(sorted([(u1, v1), (u2, v2)]))
                    if key in seen:
                        continue
                    seen.add(key)
                    t = adj.copy()
                    _switch(t, u1, v1, u2, v2)
                    if not is_valid(t):
                        continue
                    ds, dx = int(total_squares(t)) - s0, int(surplus(t)) - x0
                    out.append((-16.0 * ds + 4.0 * lam * dx, ds, dx, u1, v1, u2, v2))
    return out


def region(adj, bg_c):
    c = square_counts(adj)
    return np.flatnonzero(c != bg_c), c


def report(name, adj, part, bg_c, neutral=False, symmetry=True):
    n = adj.shape[0]
    reg, c = region(adj, bg_c)
    s, x = int(total_squares(adj)), int(surplus(adj))
    h = float(hamiltonian(adj, LAM))
    line = 16.0 * (n - bg_c * n / 4.0)          # H of a graph whose every point touches bg_c squares, X = 0
    print("\n%s: N = %d, S = %d, X = %d, H = %.0f (%+.0f against %d squares at every point)" % (name, n, s, x, h, h - line, bg_c))
    print("  points by squares touched:", {int(k): int(v) for k, v in enumerate(np.bincount(c)) if v})
    pats = Counter(link_pattern(adj, int(v)) for v in (reg if len(reg) else range(n)))
    print("  squares on the links of the %s points:" % ("planted" if len(reg) else "(all)"), dict(pats))
    if symmetry:
        try:
            from graphity import symmetry as sym
            print("  side-preserving symmetries:", sym.count(adj, part))
        except ImportError:
            pass
    near_reg = np.flatnonzero((part == 0) & (distances(adj, reg if len(reg) else [0]) <= 1))
    if not len(reg):
        near_reg = near_reg[:1]                  # a homogeneous background: every side-0 point is alike
    mv = switches(adj, part, near_reg)
    kinds = Counter((m[0], m[1], m[2]) for m in mv)
    print("  cheapest switches touching a side-0 point within 1 of the region (%d points):" % len(near_reg))
    for (cost, ds, dx), k in sorted(kinds.items())[:5]:
        print("    dH %+4.0f  (dS %+d, dX %+d): %d switches" % (cost, ds, dx, k))
    down = [m for m in mv if m[0] < 0]
    print("  downhill single switches: %d" % len(down))
    if neutral and not down:
        # Is the region held by a wall, or only by the need to find one zero-cost switch first? Try the zero-cost
        # switches in a fixed order and stop at the first after which a downhill switch exists within 3 of it.
        zero = [m for m in mv if m[0] == 0]
        found = None
        for k, m in enumerate(zero, 1):
            t = adj.copy()
            _switch(t, *m[3:])
            local = np.flatnonzero((part == 0) & (distances(t, list(m[3:])) <= 3))
            nb = min(switches(t, part, local))
            if nb[0] < 0:
                found = (k, nb)
                break
        if found:
            print("  one zero-cost switch opens a downhill one (switch %d of %d tried; next: dH %+.0f, dS %+d, dX %+d)" % (
                found[0], len(zero), found[1][0], found[1][1], found[1][2]))
        else:
            print("  none of the %d zero-cost switches opens a downhill switch" % len(zero))
    return dict(N=n, S=s, X=x, H=h, excess=h - line, region=len(reg), cheapest=min(kinds), downhill=len(down))


def descend(adj, part, bg_c, steps):
    """Zero temperature: take the most downhill switch near the non-background points; if there is none, take the
    first zero-cost switch (fixed order) after which a downhill one exists within 3; stop when neither exists.
    One path, not all of them: it shows that no energy barrier holds the region, not how a chain at g > 0 leaves it."""
    adj = adj.copy()
    h0 = float(hamiltonian(adj, LAM))
    for step in range(steps):
        reg, c = region(adj, bg_c)
        near = np.flatnonzero((part == 0) & (distances(adj, reg if len(reg) else [0]) <= 2))
        mv = switches(adj, part, near)
        best = min(mv)
        if best[0] < 0:
            _switch(adj, *best[3:])
            kind = "downhill %+.0f" % best[0]
        else:
            got = None
            for z in (m for m in mv if m[0] == 0):
                t = adj.copy()
                _switch(t, *z[3:])
                if min(switches(t, part, np.flatnonzero((part == 0) & (distances(t, list(z[3:])) <= 3))))[0] < 0:
                    got = z
                    break
            if got is None:
                print("    stop: no downhill switch, and none within one zero-cost switch")
                break
            _switch(adj, *got[3:])
            kind = "zero-cost"
        reg, c = region(adj, bg_c)
        print("    step %2d %-13s H %.0f (%+.0f); points by squares touched %s" % (
            step + 1, kind, hamiltonian(adj, LAM), hamiltonian(adj, LAM) - h0,
            {int(k): int(v) for k, v in enumerate(np.bincount(c)) if v}))
    return adj


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("--size", type=int, default=240, choices=sorted(GROUPS))
    ap.add_argument("--flat", type=int, default=14)
    ap.add_argument("--neutral", action="store_true")
    ap.add_argument("--save", default=None)
    ap.add_argument("--descend", type=int, default=0, help="also follow a zero-temperature path this many switches")
    args = ap.parse_args(argv)
    objs = build_all(args.size, args.flat)
    for name, (adj, part, bg_c) in objs.items():
        report(name, adj, part, bg_c, neutral=args.neutral)
        if args.descend and name in ("hyperbolic_fold", "hyperbolic_handle", "flat_handle"):
            print("  zero-temperature path:")
            descend(adj, part, bg_c, args.descend)
        if args.save:
            Path(args.save).mkdir(parents=True, exist_ok=True)
            np.savez(Path(args.save) / (name + ".npz"), adj=adj, part=part)


if __name__ == "__main__":
    main(sys.argv[1:])
